[project]
name = "aws-cdk-agent-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bedrock-agentcore>=1.2.1",
    "strands-agents>=1.25.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.0",
]


[lint]
ignore = [
  "E501",  # line too long
]

select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # isort
]